/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReactionsRouteImport } from './routes/reactions'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as SplatRouteImport } from './routes/$'

const ReactionsRoute = ReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/comments': typeof CommentsRoute
  '/reactions': typeof ReactionsRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/comments': typeof CommentsRoute
  '/reactions': typeof ReactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/comments': typeof CommentsRoute
  '/reactions': typeof ReactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/comments' | '/reactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/comments' | '/reactions'
  id: '__root__' | '/$' | '/comments' | '/reactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  CommentsRoute: typeof CommentsRoute
  ReactionsRoute: typeof ReactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reactions': {
      id: '/reactions'
      path: '/reactions'
      fullPath: '/reactions'
      preLoaderRoute: typeof ReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  CommentsRoute: CommentsRoute,
  ReactionsRoute: ReactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
